import { Deployment, LogEntry, Notification, Service, ApiKey, SystemMetrics, MetricPoint } from '@/types'

function generateMetricPoints(hours: number, base: number, variance: number): MetricPoint[] {
  const points: MetricPoint[] = []
  const now = Date.now()
  const interval = (hours * 3600000) / 60
  for (let i = 60; i >= 0; i--) {
    points.push({
      timestamp: new Date(now - i * interval).toISOString(),
      value: Math.max(0, base + (Math.random() - 0.5) * variance * 2),
    })
  }
  return points
}

export const mockMetrics: SystemMetrics = {
  cpu: {
    name: 'CPU Usage',
    data: generateMetricPoints(24, 42, 20),
    unit: '%',
    current: 43.2,
    min: 12.1,
    max: 87.4,
    avg: 42.7,
  },
  memory: {
    name: 'Memory Usage',
    data: generateMetricPoints(24, 68, 15),
    unit: '%',
    current: 68.5,
    min: 52.3,
    max: 89.1,
    avg: 67.2,
  },
  network: {
    in: {
      name: 'Network In',
      data: generateMetricPoints(24, 15, 10),
      unit: 'MB/s',
      current: 14.3,
      min: 2.1,
      max: 42.7,
      avg: 15.1,
    },
    out: {
      name: 'Network Out',
      data: generateMetricPoints(24, 8, 6),
      unit: 'MB/s',
      current: 7.8,
      min: 1.2,
      max: 22.4,
      avg: 8.3,
    },
  },
  disk: {
    name: 'Disk Usage',
    data: generateMetricPoints(24, 54, 5),
    unit: '%',
    current: 54.2,
    min: 48.1,
    max: 61.3,
    avg: 53.9,
  },
  responseTime: {
    name: 'Response Time',
    data: generateMetricPoints(24, 145, 80),
    unit: 'ms',
    current: 142,
    min: 48,
    max: 892,
    avg: 153,
  },
  errorRate: {
    name: 'Error Rate',
    data: generateMetricPoints(24, 0.8, 1.2),
    unit: '%',
    current: 0.7,
    min: 0,
    max: 4.2,
    avg: 0.9,
  },
  uptime: 99.94,
  requestsPerMinute: 2847,
}

export const mockDeployments: Deployment[] = [
  {
    id: 'dep-001',
    name: 'api-gateway-prod',
    status: 'running',
    source: 'github',
    branch: 'main',
    commit: 'a3f8d92',
    commitMessage: 'feat: add rate limiting middleware',
    author: 'Sarah Chen',
    region: 'us-east-1',
    url: 'https://api-gateway.infrapilot.app',
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    duration: 142000,
    version: 'v2.4.1',
    previousVersion: 'v2.4.0',
    tags: ['production', 'api'],
    replicas: 3,
    cpu: 34.2,
    memory: 67.8,
    buildSettings: {
      buildCommand: 'npm run build',
      startCommand: 'node dist/index.js',
      rootDirectory: '/',
      nodeVersion: '20.x',
      envVariables: [
        { key: 'NODE_ENV', value: 'production', isSecret: false },
        { key: 'DATABASE_URL', value: '****', isSecret: true },
        { key: 'REDIS_URL', value: '****', isSecret: true },
        { key: 'PORT', value: '3000', isSecret: false },
      ],
    },
    pipeline: [
      { id: 'p1', name: 'Clone Repository', status: 'success', duration: 3200 },
      { id: 'p2', name: 'Install Dependencies', status: 'success', duration: 28400 },
      { id: 'p3', name: 'Run Tests', status: 'success', duration: 45600 },
      { id: 'p4', name: 'Build', status: 'success', duration: 38200 },
      { id: 'p5', name: 'Deploy', status: 'success', duration: 26600 },
    ],
  },
  {
    id: 'dep-002',
    name: 'frontend-dashboard',
    status: 'building',
    source: 'github',
    branch: 'feature/new-ui',
    commit: 'b7c4e21',
    commitMessage: 'redesign: update dashboard layout',
    author: 'Marcus Rivera',
    region: 'eu-west-1',
    url: 'https://dashboard.infrapilot.app',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    updatedAt: new Date(Date.now() - 300000).toISOString(),
    duration: 0,
    version: 'v3.1.0',
    tags: ['staging', 'frontend'],
    replicas: 2,
    cpu: 0,
    memory: 0,
    buildSettings: {
      buildCommand: 'npm run build',
      startCommand: 'npx serve dist',
      rootDirectory: '/',
      nodeVersion: '20.x',
      envVariables: [
        { key: 'VITE_API_URL', value: 'https://api.infrapilot.app', isSecret: false },
        { key: 'VITE_ENV', value: 'staging', isSecret: false },
      ],
    },
    pipeline: [
      { id: 'p1', name: 'Clone Repository', status: 'success', duration: 2800 },
      { id: 'p2', name: 'Install Dependencies', status: 'success', duration: 31200 },
      { id: 'p3', name: 'Run Tests', status: 'running', duration: 0 },
      { id: 'p4', name: 'Build', status: 'pending' },
      { id: 'p5', name: 'Deploy', status: 'pending' },
    ],
  },
  {
    id: 'dep-003',
    name: 'ml-inference-service',
    status: 'failed',
    source: 'docker',
    branch: 'main',
    commit: 'c9d2f55',
    commitMessage: 'update: upgrade torch to 2.2.0',
    author: 'Priya Patel',
    region: 'ap-southeast-1',
    url: 'https://ml.infrapilot.app',
    createdAt: new Date(Date.now() - 4 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3.5 * 3600000).toISOString(),
    duration: 78000,
    version: 'v1.8.2',
    previousVersion: 'v1.8.1',
    tags: ['ml', 'gpu'],
    replicas: 1,
    cpu: 0,
    memory: 0,
    buildSettings: {
      buildCommand: 'docker build -t ml-inference .',
      startCommand: 'python serve.py',
      rootDirectory: '/',
      nodeVersion: '20.x',
      envVariables: [
        { key: 'MODEL_PATH', value: '/models/v2', isSecret: false },
        { key: 'API_KEY', value: '****', isSecret: true },
      ],
    },
    pipeline: [
      { id: 'p1', name: 'Pull Docker Image', status: 'success', duration: 12000 },
      { id: 'p2', name: 'Build Container', status: 'success', duration: 45000 },
      { id: 'p3', name: 'Health Check', status: 'failed', duration: 21000 },
      { id: 'p4', name: 'Route Traffic', status: 'skipped' },
    ],
  },
  {
    id: 'dep-004',
    name: 'worker-queue-service',
    status: 'running',
    source: 'github',
    branch: 'main',
    commit: 'e1a9b33',
    commitMessage: 'fix: memory leak in job processor',
    author: 'James Kim',
    region: 'us-west-2',
    url: 'https://worker.infrapilot.app',
    createdAt: new Date(Date.now() - 6 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
    duration: 98000,
    version: 'v1.12.0',
    tags: ['background', 'queue'],
    replicas: 5,
    cpu: 28.7,
    memory: 45.3,
    buildSettings: {
      buildCommand: 'npm run build',
      startCommand: 'node worker.js',
      rootDirectory: '/packages/worker',
      nodeVersion: '18.x',
      envVariables: [
        { key: 'REDIS_URL', value: '****', isSecret: true },
        { key: 'CONCURRENCY', value: '10', isSecret: false },
      ],
    },
    pipeline: [
      { id: 'p1', name: 'Clone Repository', status: 'success', duration: 3100 },
      { id: 'p2', name: 'Install Dependencies', status: 'success', duration: 22800 },
      { id: 'p3', name: 'Run Tests', status: 'success', duration: 41200 },
      { id: 'p4', name: 'Build', status: 'success', duration: 18600 },
      { id: 'p5', name: 'Deploy', status: 'success', duration: 12300 },
    ],
  },
  {
    id: 'dep-005',
    name: 'notification-service',
    status: 'stopped',
    source: 'zip',
    branch: 'main',
    commit: 'f2c7a14',
    commitMessage: 'chore: dependency updates',
    author: 'Alex Torres',
    region: 'us-east-1',
    url: 'https://notify.infrapilot.app',
    createdAt: new Date(Date.now() - 12 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600000).toISOString(),
    duration: 54000,
    version: 'v0.9.4',
    tags: ['notifications', 'email'],
    replicas: 0,
    cpu: 0,
    memory: 0,
    buildSettings: {
      buildCommand: 'npm run build',
      startCommand: 'node index.js',
      rootDirectory: '/',
      nodeVersion: '20.x',
      envVariables: [
        { key: 'SMTP_HOST', value: 'smtp.infrapilot.app', isSecret: false },
        { key: 'SMTP_PASS', value: '****', isSecret: true },
      ],
    },
    pipeline: [
      { id: 'p1', name: 'Extract Archive', status: 'success', duration: 1200 },
      { id: 'p2', name: 'Install Dependencies', status: 'success', duration: 18900 },
      { id: 'p3', name: 'Build', status: 'success', duration: 22400 },
      { id: 'p4', name: 'Deploy', status: 'success', duration: 11500 },
    ],
  },
  {
    id: 'dep-006',
    name: 'auth-service',
    status: 'running',
    source: 'github',
    branch: 'main',
    commit: 'g4h8k22',
    commitMessage: 'security: update JWT secret rotation',
    author: 'Sarah Chen',
    region: 'us-east-1',
    url: 'https://auth.infrapilot.app',
    createdAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 23 * 3600000).toISOString(),
    duration: 112000,
    version: 'v3.7.2',
    tags: ['auth', 'security', 'production'],
    replicas: 4,
    cpu: 18.4,
    memory: 52.1,
    buildSettings: {
      buildCommand: 'go build -o auth-service .',
      startCommand: './auth-service',
      rootDirectory: '/',
      nodeVersion: '20.x',
      envVariables: [
        { key: 'JWT_SECRET', value: '****', isSecret: true },
        { key: 'DB_URL', value: '****', isSecret: true },
      ],
    },
    pipeline: [
      { id: 'p1', name: 'Clone Repository', status: 'success', duration: 2900 },
      { id: 'p2', name: 'Build Go Binary', status: 'success', duration: 58000 },
      { id: 'p3', name: 'Run Tests', status: 'success', duration: 32100 },
      { id: 'p4', name: 'Deploy', status: 'success', duration: 19000 },
    ],
  },
]

export const mockLogs: LogEntry[] = [
  { id: 'log-001', timestamp: new Date(Date.now() - 30000).toISOString(), severity: 'info', service: 'api-gateway', deploymentId: 'dep-001', message: 'Server started on port 3000', traceId: 'trace-abc123' },
  { id: 'log-002', timestamp: new Date(Date.now() - 25000).toISOString(), severity: 'info', service: 'api-gateway', deploymentId: 'dep-001', message: 'Connected to database pool (10 connections)', traceId: 'trace-abc124' },
  { id: 'log-003', timestamp: new Date(Date.now() - 20000).toISOString(), severity: 'warn', service: 'api-gateway', deploymentId: 'dep-001', message: 'Rate limit threshold reached for IP 192.168.1.45 (98/100 req/min)', traceId: 'trace-abc125' },
  { id: 'log-004', timestamp: new Date(Date.now() - 18000).toISOString(), severity: 'error', service: 'ml-inference', deploymentId: 'dep-003', message: 'Health check failed: container exited with code 137 (OOMKilled)', traceId: 'trace-def456' },
  { id: 'log-005', timestamp: new Date(Date.now() - 15000).toISOString(), severity: 'info', service: 'worker-queue', deploymentId: 'dep-004', message: 'Processed 1,247 jobs in last 60 seconds', traceId: 'trace-ghi789' },
  { id: 'log-006', timestamp: new Date(Date.now() - 12000).toISOString(), severity: 'debug', service: 'auth-service', deploymentId: 'dep-006', message: 'JWT token validated for user id: usr-8821', traceId: 'trace-jkl012' },
  { id: 'log-007', timestamp: new Date(Date.now() - 10000).toISOString(), severity: 'error', service: 'api-gateway', deploymentId: 'dep-001', message: 'Upstream timeout after 30000ms for POST /api/v1/inference', traceId: 'trace-mno345' },
  { id: 'log-008', timestamp: new Date(Date.now() - 8000).toISOString(), severity: 'info', service: 'auth-service', deploymentId: 'dep-006', message: 'New user registration: user@example.com', traceId: 'trace-pqr678' },
  { id: 'log-009', timestamp: new Date(Date.now() - 6000).toISOString(), severity: 'warn', service: 'worker-queue', deploymentId: 'dep-004', message: 'Job queue depth exceeding warning threshold: 2,841 pending jobs', traceId: 'trace-stu901' },
  { id: 'log-010', timestamp: new Date(Date.now() - 4000).toISOString(), severity: 'info', service: 'api-gateway', deploymentId: 'dep-001', message: 'GET /api/v1/health → 200 OK (12ms)', traceId: 'trace-vwx234' },
  { id: 'log-011', timestamp: new Date(Date.now() - 3000).toISOString(), severity: 'fatal', service: 'ml-inference', deploymentId: 'dep-003', message: 'Process terminated: Segmentation fault in CUDA kernel', traceId: 'trace-yza567' },
  { id: 'log-012', timestamp: new Date(Date.now() - 2000).toISOString(), severity: 'info', service: 'api-gateway', deploymentId: 'dep-001', message: 'POST /api/v1/deploy → 202 Accepted (48ms)', traceId: 'trace-bcd890' },
  { id: 'log-013', timestamp: new Date(Date.now() - 1000).toISOString(), severity: 'debug', service: 'auth-service', deploymentId: 'dep-006', message: 'Session refreshed for user usr-3341, TTL extended by 3600s', traceId: 'trace-efg123' },
  { id: 'log-014', timestamp: new Date(Date.now() - 500).toISOString(), severity: 'info', service: 'worker-queue', deploymentId: 'dep-004', message: 'Heartbeat OK — all 5 replicas healthy', traceId: 'trace-hij456' },
  { id: 'log-015', timestamp: new Date().toISOString(), severity: 'warn', service: 'api-gateway', deploymentId: 'dep-001', message: 'Memory pressure detected: 87% heap used, initiating GC', traceId: 'trace-klm789' },
]

export const mockNotifications: Notification[] = [
  { id: 'n1', title: 'Deployment Successful', message: 'api-gateway-prod v2.4.1 deployed to us-east-1', type: 'success', read: false, timestamp: new Date(Date.now() - 1800000).toISOString(), deploymentId: 'dep-001' },
  { id: 'n2', title: 'Build Failed', message: 'ml-inference-service health check failed after upgrade', type: 'error', read: false, timestamp: new Date(Date.now() - 3600000).toISOString(), deploymentId: 'dep-003' },
  { id: 'n3', title: 'High CPU Alert', message: 'api-gateway-prod CPU usage at 87% for 5+ minutes', type: 'warning', read: false, timestamp: new Date(Date.now() - 5400000).toISOString(), deploymentId: 'dep-001' },
  { id: 'n4', title: 'Deployment Started', message: 'frontend-dashboard build initiated by Marcus Rivera', type: 'info', read: true, timestamp: new Date(Date.now() - 7200000).toISOString(), deploymentId: 'dep-002' },
  { id: 'n5', title: 'Service Stopped', message: 'notification-service was manually stopped', type: 'warning', read: true, timestamp: new Date(Date.now() - 9000000).toISOString(), deploymentId: 'dep-005' },
]

export const mockServices: Service[] = [
  { id: 's1', name: 'api-gateway', status: 'running', uptime: 99.94, instances: 3, region: 'us-east-1', cpu: 34.2, memory: 67.8 },
  { id: 's2', name: 'auth-service', status: 'running', uptime: 99.99, instances: 4, region: 'us-east-1', cpu: 18.4, memory: 52.1 },
  { id: 's3', name: 'worker-queue', status: 'running', uptime: 99.87, instances: 5, region: 'us-west-2', cpu: 28.7, memory: 45.3 },
  { id: 's4', name: 'ml-inference', status: 'stopped', uptime: 94.23, instances: 0, region: 'ap-southeast-1', cpu: 0, memory: 0 },
  { id: 's5', name: 'notification', status: 'stopped', uptime: 98.12, instances: 0, region: 'us-east-1', cpu: 0, memory: 0 },
  { id: 's6', name: 'frontend', status: 'starting', uptime: 100, instances: 2, region: 'eu-west-1', cpu: 12.1, memory: 38.4 },
]

export const mockApiKeys: ApiKey[] = [
  { id: 'k1', name: 'Production CI/CD', key: 'ip_live_xK9mN2pQ...', createdAt: new Date(Date.now() - 30 * 86400000).toISOString(), lastUsed: new Date(Date.now() - 3600000).toISOString(), permissions: ['read', 'write', 'deploy'] },
  { id: 'k2', name: 'Monitoring Dashboard', key: 'ip_live_aB7cD4eF...', createdAt: new Date(Date.now() - 15 * 86400000).toISOString(), lastUsed: new Date(Date.now() - 300000).toISOString(), permissions: ['read'] },
  { id: 'k3', name: 'Development Key', key: 'ip_test_gH1iJ5kL...', createdAt: new Date(Date.now() - 5 * 86400000).toISOString(), lastUsed: null, permissions: ['read', 'write'] },
]

export const mockDeploymentTrend = Array.from({ length: 30 }, (_, i) => ({
  date: new Date(Date.now() - (29 - i) * 86400000).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
  successful: Math.floor(Math.random() * 12) + 3,
  failed: Math.floor(Math.random() * 3),
}))

export const mockActivityFeed = [
  { id: 'a1', type: 'deployment', message: 'api-gateway-prod deployed successfully', user: 'Sarah Chen', timestamp: new Date(Date.now() - 1800000).toISOString() },
  { id: 'a2', type: 'alert', message: 'High memory usage on worker-queue-service', user: 'System', timestamp: new Date(Date.now() - 3200000).toISOString() },
  { id: 'a3', type: 'deployment', message: 'frontend-dashboard build started', user: 'Marcus Rivera', timestamp: new Date(Date.now() - 4800000).toISOString() },
  { id: 'a4', type: 'rollback', message: 'ml-inference-service rollback initiated', user: 'Priya Patel', timestamp: new Date(Date.now() - 7200000).toISOString() },
  { id: 'a5', type: 'config', message: 'auth-service env variables updated', user: 'James Kim', timestamp: new Date(Date.now() - 9000000).toISOString() },
]